M08 build test data
Code-Institute-Community/ci-hackathon-app pull request #104
Opened 2020-10-26 23:47 UTC by Sarosim

## Description

This PR adds data to the following models:
### accounts app:
- CustomUser
### hackathon app
- Hackathon
- HackTeam
- HackProject
- HackProjectScoreCategory

## Pull request type
M08 build test data
- [X] #M01 (Miscellaneous User Story #01)
- [ ] #P02 (Participant User Story #02)
- [ ] #S03 (Staff User Story #03)
- [ ] #A04 (Admin User Story #04)
- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe):

## Related Issue

## Configuration instructions

profiles.json contains 20 users as per the screen shots below
`score_categories.json` contains the 5 Score Categories we use,
`hackathon#1.json` contains the events, projects, teams and the score categories as well

## Testing

## Screenshots

Added 1 superuser on top of the existing admin
![image](https://user-images.githubusercontent.com/44575078/97239988-e496c300-17e4-11eb-8f02-e957028736bb.png)

4 other staff, with no superuser status
![image](https://user-images.githubusercontent.com/44575078/97240033-10b24400-17e5-11eb-8477-d0084bc381d6.png)

14 participants:
![image](https://user-images.githubusercontent.com/44575078/97240076-2f183f80-17e5-11eb-9188-ac60555bfaa9.png)

Project Score Categories:
![image](https://user-images.githubusercontent.com/44575078/97240111-46efc380-17e5-11eb-92ed-2526fb438a79.png)

Projects (both belong to the same event):
![image](https://user-images.githubusercontent.com/44575078/97240143-64249200-17e5-11eb-81a4-140fac8d187b.png)

Teams (belonging to two events):
![image](https://user-images.githubusercontent.com/44575078/97240188-81596080-17e5-11eb-8dd8-7ce361f1ea0d.png)

and four events:
![image](https://user-images.githubusercontent.com/44575078/97240210-946c3080-17e5-11eb-85d0-a0142c93bfcc.png)

## Additional Information

## Does this introduce a breaking change

- [ ] Yes
- [X] No

2020-10-27 13:27 UTC, stefdworschak requested changes
@Sarosim the PR looks good. Could you please also add a command to the `scripts/seed.sh` and `scripts/seed.bat` files to seed these fixtures too?

2020-10-27 13:27 UTC, stefdworschak commented on accounts/fixtures/profiles.json
> +Postgres DATABASE_URL not found, using db.sqlite3
I think this file is not needed. I already added a file to `accounts/fixtures` to do this for one admin user and we probably don't need more.

2020-10-27 13:27 UTC, stefdworschak commented on hackathon/fixtures/hackathon#1.json
> +Postgres DATABASE_URL not found, using db.sqlite3
Can you remove this line? Same for the other files.

2020-10-27 13:27 UTC, stefdworschak commented on hackathon/fixtures/hackathon#1.json
> +Postgres DATABASE_URL not found, using db.sqlite3
Also, could you change the name of the file please? Just `hackathons` is fine.

2020-10-27 13:28 UTC, stefdworschak commented on accounts/fixtures/profiles.json
> +Postgres DATABASE_URL not found, using db.sqlite3
Sorry ignore this please. Just saw that you added quite a lot, so let's leave these in! :+1:

2020-10-27 16:33 UTC, Sarosim commented
All done, also removed the organisation part from my profiles fixture as it is done by `organisation.json`
score categories are also part of the `hackathons.json`, so I haven't included `score_categories.json` in the scripts, but can be useful to just load them separately.

2020-10-28 15:53 UTC, stefdworschak approved these changes
LGTM

2020-10-28 15:54 UTC, merged