#P04.1. Only display published Hackathons
Code-Institute-Community/ci-hackathon-app pull request #105
Opened 2020-10-27 11:21 UTC by natalijabujevic0708

## Description
Added an if statement on hackathon_list.html to show only Hackathons with status published

## Pull request type
#P04.1. Only display published Hackathons

## Testing

## Screenshots

BEFORE:
![before](https://user-images.githubusercontent.com/67863074/97294765-55ba9280-1846-11eb-8481-d1edf19cda4a.png)

AFTER:
![after](https://user-images.githubusercontent.com/67863074/97294803-63701800-1846-11eb-8234-cff457821e82.png)

## Does this introduce a breaking change

- [ ] Yes
- [X] No

2020-10-27 13:36 UTC, stefdworschak requested changes
@natalijabujevic0708 please have a quick look at my comment and let me know once I can approve it.

2020-10-27 13:36 UTC, stefdworschak commented on hackathon/templates/hackathon/hackathon_list.html
> +        {%if hackathon.status == 'published' %}
Could you change this to be either `published` or `draft` and created by the current user?

2020-10-27 13:36 UTC, stefdworschak commented
Also, it seems you have a merge conflict. Please resolve that before reverting back to me.

2020-10-27 15:32 UTC, natalijabujevic0708 commented
@stefdworschak I did the changes and tested it. So I created 2 Hackathos with status draft, one created by me and other by admin. At the site I could only see the draft created by me, and a published Hackathon created by admin!
![admin](https://user-images.githubusercontent.com/67863074/97323665-ef933700-1868-11eb-8e47-13cf0cb59b20.png)
![display](https://user-images.githubusercontent.com/67863074/97324248-8829b700-1869-11eb-96d1-65eb2836c82c.png)

2020-10-28 15:51 UTC, stefdworschak approved these changes
LGTM

2020-10-28 15:51 UTC, merged