Participant profile page
Code-Institute-Community/ci-hackathon-app pull request #110
Opened 2020-10-29 20:22 UTC by Jays-T

## Description

This adds a user dashboard/control panel for the profile page.

## Pull request type

feature/profile page dashboard/control panel

## Testing

Tested using dev tools in Chrome

## Screenshots

![CI_hackathon_Profile_Dashb](https://user-images.githubusercontent.com/59046774/97628245-bc010a00-1a2c-11eb-950e-4ce7e2aeeb53.png)
![CI_hackathon_Profile_Dashb_1](https://user-images.githubusercontent.com/59046774/97628277-c4594500-1a2c-11eb-88ee-57bb00129bb4.png)
![CI_hackathon_Profile_Dashb_2](https://user-images.githubusercontent.com/59046774/97628296-c91df900-1a2c-11eb-9098-b1f21c8e0b95.png)
![CI_hackathon_Profile_Dashb_3](https://user-images.githubusercontent.com/59046774/97628310-cde2ad00-1a2c-11eb-9ef1-485c01f665ed.png)

## Does this introduce a breaking change

- [ ] Yes
- [x] No

2020-10-29 20:23 UTC, auxfuse commented
@auxfuse for the in-window user demo facial expressions... 😂😂😂😂😂😂

2020-10-30 21:11 UTC, stefdworschak requested changes
@Jays-T please have a look at my comments and revert back when you have made the changes.

Overall I just think that the extra menu on the left does not offer much more functionality than the top navbar and makes the page a bit crowded. I would remove that menu and add more styling (and maybe a profile image placeholder) to the profile page to create somewhat of a portfolio. I do like the list of hackathons on the right, but if possible I would populate it with actual hackathons than just placeholders.

2020-10-30 21:57 UTC, Jays-T commented on profiles/views.py
> +# @login_required
Ah, forgot to remove that comment. I did that because I couldn't get my superuser to register (the foreign key/migrations issue).  oops... :P

2020-10-30 22:02 UTC, Jays-T commented on templates/base.html
> -</body>
Not sure, must have been done by mistake.

2020-10-30 22:27 UTC, Jays-T commented on static/js/profile.js
> +window.onload = function() {
Well, as it turns out neither vanilla or jQuery are required since the user-panel won't be used for the project. :)

2020-10-30 22:35 UTC, Jays-T commented on profiles/urls.py
> +    path("user", views.profile, name="profile"),
Reverted back to naming convention of profile, I believe the original profile page submitted by someone else had 'user' put into the url path and I just hadn't changed it or looked at it.

2020-10-30 22:44 UTC, Jays-T commented on accounts/migrations/0001_initial.py
> -# Generated by Django 3.1.1 on 2020-10-22 15:25
I'm not sure what you mean by add a new migration? I haven't changed/edited any existing migrations. Each time I've done a pull from upstream, then deleted my database and run migrations.

2020-10-30 23:38 UTC, Jays-T commented
![CI_hackathon_Profile](https://user-images.githubusercontent.com/59046774/97764997-c7c5fc80-1b10-11eb-86fd-b9c855fb95d0.png)

Didn't get to rendering actual hackathons in the hackathon hall. I'll most likely start a new branch and open a separate Issue for that, what to you think @stefdworschak ?

2020-10-31 00:09 UTC, stefdworschak approved these changes
@Jays-T Have a look at my comment re the migration. If you can't change it please let me know and we can have a look at it together tomorrow.

2020-10-31 00:09 UTC, stefdworschak commented on accounts/migrations/0001_initial.py
> -# Generated by Django 3.1.1 on 2020-10-22 15:25
Not exactly sure what happened. Maybe somehow in the merge, but just revert the changes, maybe manually in the file. Then run `python manage.py makemigrations` and it should (if necessary) create a new migration file instead.

2020-10-31 13:44 UTC, stefdworschak commented
LGTM

2020-10-31 13:45 UTC, merged