#M01. Judging automation - calculate and display total scores
Code-Institute-Community/ci-hackathon-app pull request #120
Opened 2020-11-06 17:30 UTC by natalijabujevic0708

## Description
Updated the check_projects_scores function so If all the projects were scored, it calculates the total score for each team, sorts the teams by scores and renders final_score.html with the score table.
If all projects weren't scored, it renders final_score.html without the score table.

## Pull request type

#M01. Judging automation 

## Testing
I created Hackathon 1:

- teams: Team 1 with Project 1, Team 2 with Project Team 2 and Team 3 with Project Team 3
- judges: natalija, admin
- categories: Design, Function

**First scenario:**
1. Judge admin scored all the projects in all categories but judge natalija scored only teams 2 and 3

![admin_2_score](https://user-images.githubusercontent.com/67863074/98393863-d0a75880-2051-11eb-88b9-5e0b7150deea.png)

2. After the judge natalija scored team 1, final_score.html is rendered with the score table

![judging_2_score](https://user-images.githubusercontent.com/67863074/98394048-16fcb780-2052-11eb-8ac0-4f47cd80a360.png)

![table_2_scores](https://user-images.githubusercontent.com/67863074/98394056-1a903e80-2052-11eb-8089-9c47ec8e1609.png)

**==> if all the projects are scored,  it calculates the total score for each team, sorts the teams by scores and renders final_score.html with the score table**

**Testing the url path:**
If the url path is written with the specific hack_id it displays the same results
![url3](https://user-images.githubusercontent.com/67863074/98396349-8031fa00-2055-11eb-8397-2ca6efa436f3.png)

**Second scenario:**
1. Judge admin scored all the projects in all categories but judge natalija scored only team 2

![admin_4_scores](https://user-images.githubusercontent.com/67863074/98394267-680cab80-2052-11eb-8a41-1f2af2f4565b.png)

2. After the judge natalija scored team 1, final_score.html is rendered without the score table because the judge still needs to score team 3

![judging_4_scores](https://user-images.githubusercontent.com/67863074/98394341-807cc600-2052-11eb-9475-6d33fc143610.png)

![table_4_scores](https://user-images.githubusercontent.com/67863074/98394346-84104d00-2052-11eb-9b75-a059634842a8.png)

**==> If all projects weren't scored, it renders final_score.html without the score table**

**Testing the url path:**

If the url path is written with the specific hack_id it displays the same results

![url](https://user-images.githubusercontent.com/67863074/98394639-f8e38700-2052-11eb-87b8-8942bc974433.png)

## Additional Information
There is one part of judging automation left to develop - to trigger the winning team's profile to allow them to update their shipping address.

## Does this introduce a breaking change

- [ ] Yes
- [x] No

2020-11-09 13:17 UTC, TravelTimN commented
@natalijabujevic0708 
Is this also related to #112 presumably, yeah?

2020-11-09 15:30 UTC, natalijabujevic0708 commented
@TravelTimN yes, in #112 I just checked if all the judges scored all the projects, in this pull request I calculated the scores and displayed them!

2020-11-16 09:16 UTC, TravelTimN requested changes
@natalijabujevic0708 
Looking great! A few minor adjustments/comments, and should be grand!

2020-11-16 09:16 UTC, TravelTimN commented on hackathon/templates/hackathon/final_score.html
> +		<tr class="table_titles">
Would it be more semantically acceptable to use `<thead>` and then `<tbody>` for this particular table?

2020-11-16 09:16 UTC, TravelTimN commented on hackathon/templates/hackathon/final_score.html
> +			<td>{{ team.0}}</td>
Missing a minor "space" after 0

2020-11-16 09:16 UTC, TravelTimN commented on hackathon/templates/hackathon/final_score.html
> +	{% endblock %}
File needs a blank line at the end.

2020-11-16 09:16 UTC, TravelTimN commented on static/css/style.css
> +    color: white;
Remember to use the CSS `:root` variable for `var(--white);` where applicable.

2020-11-16 09:16 UTC, TravelTimN commented on static/css/style.css
> +.table_titles + tr {
These targeted elements might need adjusted as well, if going for a more semantic `<thead>` and `<tbody>` format. (FYI)

2020-11-17 15:32 UTC, natalijabujevic0708 commented
@TravelTimN done :)

2020-11-30 11:37 UTC, TravelTimN approved these changes
LGTM

2020-11-30 11:38 UTC, merged