change the layout for the Footer and style it
Code-Institute-Community/ci-hackathon-app pull request #86
Opened 2020-10-20 00:46 UTC by nahed2019

**Description:**

Just rearrange the layout of footer and style it.
this first try I just want to learn how we can contribute. 

**Related Issue:**

Link to the related Issue

**Configuration instructions:**

List any non-trivial configuration instructions (if any)

**Testing:

![image](https://user-images.githubusercontent.com/55049113/96526042-d1cc3d80-127c-11eb-8584-7a2ec12a791c.png)

Explain what kind of testing was performed and list any testing instructions (if needed)

**Screenshots:**

Add any screenshots (if needed)

**Additional Information:**

Any other information that is needed

2020-10-20 08:15 UTC, Eventyret commented on static/css/style.css
>  footer h4 {
Would suggest to target with `id` or `class` instead of using `elements` like `h4` if this changes to anything else the CSS breaks.

2020-10-20 08:16 UTC, Eventyret commented on templates/includes/footer.html
> +	<hr>
`<hr>` are normally deprecated so would suggest using CSS to create the border

2020-10-20 09:29 UTC, stefdworschak requested changes
@nahed2019 could you make the changes Simen requested and tag me in this once done to approve it?

2020-10-20 09:37 UTC, nahed2019 commented
Yes, sure I will do it today night thanks.

On Tue, Oct 20, 2020, 11:29 Stefan Dworschak <notifications@github.com>
wrote:

> *@stefdworschak* requested changes on this pull request.
>
> @nahed2019 <https://github.com/nahed2019> could you make the changes
> Simen requested and tag me in this once done to approve it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Code-Institute-Community/ci-hackathon-app/pull/86#pullrequestreview-512511313>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AND7XGJZ2POQWDPHM4OX2IDSLVKA5ANCNFSM4SXDN7VA>
> .
>

2020-10-20 12:00 UTC, auxfuse commented
Can I ask why we are restyling the Footer that has already been a previously approved PR request and was structured inline with the CI template? The orange icons are garishly poor against the native grey background theme color and the way it was prior was much better in terms of UX to appeal to those users who may have a visual impairments especially around color contrast. 

@Eventyret @stefdworschak @nahed2019 This PR request I am talking about btw was PR: #F01 Footer Content & Styling #53 #74

2020-10-20 22:03 UTC, nahed2019 commented
*@stefdworschak* changes were done, but I don't know if it is done in the
correct way.
Thanks for giving me a chance to learn new things.


On Tue, Oct 20, 2020, 11:29 Stefan Dworschak <notifications@github.com>
wrote:

> *@stefdworschak* requested changes on this pull request.
>
> @nahed2019 <https://github.com/nahed2019> could you make the changes
> Simen requested and tag me in this once done to approve it?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/Code-Institute-Community/ci-hackathon-app/pull/86#pullrequestreview-512511313>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AND7XGJZ2POQWDPHM4OX2IDSLVKA5ANCNFSM4SXDN7VA>
> .
>

2020-10-21 16:51 UTC, stefdworschak commented
@nahed2019 sorry for only getting back to you on this now, but after some consideration here I would like to leave the design on the footer as it is. I would suggest that we close the PR and maybe you can focus on styling some of the pages used by all_auth (see screenshot).
![image](https://user-images.githubusercontent.com/31205982/96749588-eadf0680-13c2-11eb-9788-fd5e2ca4b50c.png)

2020-10-21 16:51 UTC, closed without merging