#P03. As Participant, I would like to update my profile.
Code-Institute-Community/ci-hackathon-app pull request #98
Opened 2020-10-23 14:58 UTC by natalijabujevic0708

## Description
The users can edit their profile details:

- First Name
- Last Name
- Email Address
- Slack Display Name
- User type
- Current Module on LMS

## Pull request type
- #P03 (Participant User Story #03) As Participant, I would like to update my profile.

## Testing

All testing was done manually and the profile was successfully edited and updated.

## Screenshots

1. Original profile page.
![hackathon-app_profile_page](https://user-images.githubusercontent.com/67863074/97017276-9f089a80-1545-11eb-9078-71b2d9ce9cde.png)

2.Edit Profile
![hackathon-app_edit_profile](https://user-images.githubusercontent.com/67863074/97017385-be9fc300-1545-11eb-93c2-36e38d7baad4.png)

3. Updated Profile
![hackathon-app_edited_profile](https://user-images.githubusercontent.com/67863074/97017433-cbbcb200-1545-11eb-8ac4-ce956fa6694d.png)

## Additional Information

There is one field missing on the edit profile page:

Shipping Address

- hidden by default
- is enabled only if part of a winning team

I am planning to add it in the future as currently I don't know how to implement the condition  _enabled only if part of a winning team_

## Does this introduce a breaking change

- [ ] Yes
- [x] No

2020-10-23 16:57 UTC, stefdworschak requested changes
@natalijabujevic0708 looking very good, there are just a few minor comments from me. Overall there are also two extra things that I would like you to look at as part of this PR. 
1) Adding user_type and current_lms_module to the profile view
2) Applying some better styling to the edit profile form

2020-10-23 16:57 UTC, stefdworschak commented on accounts/templates/accounts/edit_profile.html
> +		<table>
Why did you add a table here? I don't think that's needed.

2020-10-23 16:57 UTC, stefdworschak commented on accounts/templates/accounts/edit_profile.html
> +<div class="container">
The base template already has an element with a `container` class, so I would remove this div.

2020-10-23 16:57 UTC, stefdworschak commented on accounts/views.py
> +        if form.is_valid():
I think you need to add another `else` here for when `form.is_valid()` is not `True`.

2020-10-23 16:57 UTC, stefdworschak commented on accounts/views.py
> +        contex = {
I think you mispelt context here, but I would just pass the dict directly into `render`.

2020-10-23 16:57 UTC, stefdworschak commented on accounts/forms.py
> +            'user_type',
Could you please remove this field? I don't think the user should be able to change this. Instead a change in `user_type` should come from an admin.

2020-10-23 22:21 UTC, natalijabujevic0708 commented
@stefdworschak I made the changes, let me know if everything is ok or I should change something :)

2020-10-24 12:35 UTC, stefdworschak approved these changes
LGTM

@natalijabujevic0708 we merged some more changes and it seems there is a merge conflict now, could you just resolve that and let me know once it's done so I can merge the PR?

2020-10-24 18:05 UTC, natalijabujevic0708 commented
@stefdworschak done :)

2020-10-25 12:52 UTC, merged